"""Formiq Agent Playground launcher. LOCAL DEVELOPMENT ONLY, NOT AUTHENTICATED.

Runs the existing Formiq FastAPI application, unchanged, on 127.0.0.1, and in
this process only:

- serves the playground page from the same origin (/playground/), so the
  browser calls the existing POST /coach/message without any CORS change;
- records the coach's trace metadata as it is written (the same safe metadata
  Langfuse may receive: request id, statuses, categories, counts and tool
  names, never the message, history, reply, data or instructions) and returns
  a selection of it with the coach's response as X-Playground-* headers. The
  response body is the API's own, unchanged.

The production application (uvicorn app.main:app) never imports this file:
nothing here is part of Formiq's API.

Run it from backend/, so the application reads backend/.env as usual:

    cd backend
    .venv/bin/python ../playground/server.py
"""

import argparse
import json
import sys
from contextvars import ContextVar
from pathlib import Path
from typing import Any

PLAYGROUND = Path(__file__).resolve().parent
BACKEND = PLAYGROUND.parent / "backend"
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

from fastapi import Request
from fastapi.responses import RedirectResponse
from fastapi.staticfiles import StaticFiles

from app.api.dependencies import get_tracer
from app.core.config import settings
from app.main import app
from app.observability import Tracer

# only this machine can reach the playground
HOST = "127.0.0.1"
DEFAULT_PORT = 8000
COACH_PATH = "/coach/message"
EXECUTION_HEADER = "X-Playground-Execution"
REQUEST_ID_HEADER = "X-Playground-Request-Id"
# The trace metadata the playground shows. All of it is generated by Formiq
# (app.services.coach_service, app.agent.graph): no user id, no content.
SHOWN = (
    "request_id",
    "status",
    "safety_category",
    "safety_path",
    "intent",
    "decision",
    "tools_used",
    "iterations",
    "compactions",
    "termination",
    "conversation_turns",
    "model_requests",
    "tool_calls_requested",
    "tool_calls_executed",
    "write_calls_refused",
    "decision_rejections",
    "reply_rejections",
    "compacted_tool_results",
)

# the current coach request's record; set by the middleware, filled by the backend
_record: ContextVar[dict[str, Any] | None] = ContextVar(
    "playground_record", default=None
)


class _Root:
    """The root of a request's trace: the inner backend's handle, and the
    record its metadata also goes to."""

    def __init__(self, handle: Any, record: dict[str, Any] | None) -> None:
        self.handle = handle
        self.record = record


def _inner(handle: Any) -> Any:
    return handle.handle if isinstance(handle, _Root) else handle


class RecordingBackend:
    """A tracing backend that passes every call on to the configured one
    (Langfuse, or nothing) and keeps the root's metadata for the response.
    Like any backend, it is guarded by the tracer: it cannot fail a request."""

    def __init__(self, inner: Any) -> None:
        self.inner = inner

    def start_trace(self, *, name, request_id, user_id, metadata):
        record = _record.get()
        if record is not None:
            record.update(metadata)
            record["request_id"] = request_id
        handle = self.inner.start_trace(
            name=name, request_id=request_id, user_id=user_id, metadata=metadata
        )
        return _Root(handle, record)

    def start(self, parent, *, name, kind, metadata, model):
        return self.inner.start(
            _inner(parent), name=name, kind=kind, metadata=metadata, model=model
        )

    def update(self, handle, *, metadata, level, status_message, usage):
        if isinstance(handle, _Root) and handle.record is not None:
            handle.record.update(metadata)
        self.inner.update(
            _inner(handle),
            metadata=metadata,
            level=level,
            status_message=status_message,
            usage=usage,
        )

    def end(self, handle):
        self.inner.end(_inner(handle))

    def end_trace(self, handle):
        self.inner.end_trace(_inner(handle))

    def shutdown(self):
        shutdown = getattr(self.inner, "shutdown", None)
        if shutdown is not None:
            shutdown()


def execution(record: dict[str, Any]) -> dict[str, Any]:
    """What the playground shows of a request's record."""
    return {name: record[name] for name in SHOWN if name in record}


def install() -> None:
    """Adds the playground to this process's application: the page, the
    recording tracer and the response headers. Never called in production."""
    # the configured tracer (Langfuse when enabled), with the recorder in front
    tracer = Tracer(RecordingBackend(get_tracer().backend))
    app.dependency_overrides[get_tracer] = lambda: tracer

    @app.middleware("http")
    async def execution_headers(request: Request, call_next):
        if request.url.path != COACH_PATH:
            return await call_next(request)
        record: dict[str, Any] = {}
        token = _record.set(record)
        try:
            response = await call_next(request)
        finally:
            _record.reset(token)
        if record:
            response.headers[REQUEST_ID_HEADER] = str(record.get("request_id", ""))
            response.headers[EXECUTION_HEADER] = json.dumps(execution(record))
        return response

    @app.get("/", include_in_schema=False)
    def playground_home():
        return RedirectResponse("/playground/")

    app.mount(
        "/playground",
        StaticFiles(directory=PLAYGROUND / "static", html=True),
        name="playground",
    )


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description="Formiq Agent Playground (local development only)"
    )
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    args = parser.parse_args(argv)
    if settings.app_env != "development":
        raise SystemExit(
            f"The playground runs only with APP_ENV=development (it is {settings.app_env!r})."
        )
    import uvicorn

    install()
    print(f"Formiq Agent Playground: http://localhost:{args.port}/playground/")
    print("LOCAL DEVELOPMENT ONLY — NOT AUTHENTICATED")
    uvicorn.run(app, host=HOST, port=args.port)


if __name__ == "__main__":
    main()
