"""create users and user_profiles tables

Revision ID: 4e447bdd5061
Revises: a4020d4605a0
Create Date: 2026-10-06 16:02:46.517735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e447bdd5061'
down_revision: Union[str, Sequence[str], None] = 'a4020d4605a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Double(), nullable=False),
    sa.Column('weight_kg', sa.Double(), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('fitness_experience', sa.String(length=50), nullable=False),
    sa.Column('goal', sa.String(length=50), nullable=False),
    sa.Column('target_weight_kg', sa.Double(), nullable=True),
    sa.Column('goal_period_weeks', sa.Integer(), nullable=True),
    sa.Column('training_frequency_per_week', sa.Integer(), nullable=False),
    sa.Column('training_location', sa.String(length=50), nullable=False),
    sa.Column('activity_level', sa.String(length=50), nullable=False),
    sa.Column('sleep_hours', sa.Double(), nullable=False),
    sa.Column('dietary_preference', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
